# Base image
FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy files
COPY package*.json ./
COPY . .

# Install dependencies
RUN npm install

# Expose the app port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
